import type { FxPairMetadata } from "../types";

export const FX_PAIRS: Record<string, FxPairMetadata> = {
  "EUR-USD": {
    id: "EUR-USD",
    base: "EUR",
    quote: "USD",
    name: "Euro / US Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "GBP-USD": {
    id: "GBP-USD",
    base: "GBP",
    quote: "USD",
    name: "British Pound / US Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "USD-JPY": {
    id: "USD-JPY",
    base: "USD",
    quote: "JPY",
    name: "US Dollar / Japanese Yen",
    pipSize: 0.01,
    displayDecimals: 3,
    venueLabel: "Interbank",
  },
  "AUD-USD": {
    id: "AUD-USD",
    base: "AUD",
    quote: "USD",
    name: "Australian Dollar / US Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "USD-CAD": {
    id: "USD-CAD",
    base: "USD",
    quote: "CAD",
    name: "US Dollar / Canadian Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "USD-CHF": {
    id: "USD-CHF",
    base: "USD",
    quote: "CHF",
    name: "US Dollar / Swiss Franc",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "NZD-USD": {
    id: "NZD-USD",
    base: "NZD",
    quote: "USD",
    name: "New Zealand Dollar / US Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "EUR-JPY": {
    id: "EUR-JPY",
    base: "EUR",
    quote: "JPY",
    name: "Euro / Japanese Yen",
    pipSize: 0.01,
    displayDecimals: 3,
    venueLabel: "Interbank",
  },
  "GBP-JPY": {
    id: "GBP-JPY",
    base: "GBP",
    quote: "JPY",
    name: "British Pound / Japanese Yen",
    pipSize: 0.01,
    displayDecimals: 3,
    venueLabel: "Interbank",
  },
  "USD-IDR": {
    id: "USD-IDR",
    base: "USD",
    quote: "IDR",
    name: "US Dollar / Indonesian Rupiah",
    pipSize: 1.0,
    displayDecimals: 2,
    venueLabel: "Interbank",
  },
  "EUR-GBP": {
    id: "EUR-GBP",
    base: "EUR",
    quote: "GBP",
    name: "Euro / British Pound",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "EUR-CHF": {
    id: "EUR-CHF",
    base: "EUR",
    quote: "CHF",
    name: "Euro / Swiss Franc",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "EUR-AUD": {
    id: "EUR-AUD",
    base: "EUR",
    quote: "AUD",
    name: "Euro / Australian Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "AUD-JPY": {
    id: "AUD-JPY",
    base: "AUD",
    quote: "JPY",
    name: "Australian Dollar / Japanese Yen",
    pipSize: 0.01,
    displayDecimals: 3,
    venueLabel: "Interbank",
  },
  "CAD-JPY": {
    id: "CAD-JPY",
    base: "CAD",
    quote: "JPY",
    name: "Canadian Dollar / Japanese Yen",
    pipSize: 0.01,
    displayDecimals: 3,
    venueLabel: "Interbank",
  },
  "CHF-JPY": {
    id: "CHF-JPY",
    base: "CHF",
    quote: "JPY",
    name: "Swiss Franc / Japanese Yen",
    pipSize: 0.01,
    displayDecimals: 3,
    venueLabel: "Interbank",
  },
  "SGD-IDR": {
    id: "SGD-IDR",
    base: "SGD",
    quote: "IDR",
    name: "Singapore Dollar / Indonesian Rupiah",
    pipSize: 1.0,
    displayDecimals: 2,
    venueLabel: "Interbank",
  },
  "EUR-IDR": {
    id: "EUR-IDR",
    base: "EUR",
    quote: "IDR",
    name: "Euro / Indonesian Rupiah",
    pipSize: 1.0,
    displayDecimals: 2,
    venueLabel: "Interbank",
  },
  "GBP-CHF": {
    id: "GBP-CHF",
    base: "GBP",
    quote: "CHF",
    name: "British Pound / Swiss Franc",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "EUR-SEK": {
    id: "EUR-SEK",
    base: "EUR",
    quote: "SEK",
    name: "Euro / Swedish Krona",
    pipSize: 0.0001,
    displayDecimals: 4,
    venueLabel: "Interbank",
  },
  "NZD-JPY": {
    id: "NZD-JPY",
    base: "NZD",
    quote: "JPY",
    name: "New Zealand Dollar / Japanese Yen",
    pipSize: 0.01,
    displayDecimals: 3,
    venueLabel: "Interbank",
  },
  "USD-SGD": {
    id: "USD-SGD",
    base: "USD",
    quote: "SGD",
    name: "US Dollar / Singapore Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "USD-MYR": {
    id: "USD-MYR",
    base: "USD",
    quote: "MYR",
    name: "US Dollar / Malaysian Ringgit",
    pipSize: 0.0001,
    displayDecimals: 4,
    venueLabel: "Interbank",
  },
  "AUD-NZD": {
    id: "AUD-NZD",
    base: "AUD",
    quote: "NZD",
    name: "Australian Dollar / New Zealand Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "GBP-AUD": {
    id: "GBP-AUD",
    base: "GBP",
    quote: "AUD",
    name: "British Pound / Australian Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "EUR-NZD": {
    id: "EUR-NZD",
    base: "EUR",
    quote: "NZD",
    name: "Euro / New Zealand Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "GBP-NZD": {
    id: "GBP-NZD",
    base: "GBP",
    quote: "NZD",
    name: "British Pound / New Zealand Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "EUR-CAD": {
    id: "EUR-CAD",
    base: "EUR",
    quote: "CAD",
    name: "Euro / Canadian Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "GBP-CAD": {
    id: "GBP-CAD",
    base: "GBP",
    quote: "CAD",
    name: "British Pound / Canadian Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "AUD-CAD": {
    id: "AUD-CAD",
    base: "AUD",
    quote: "CAD",
    name: "Australian Dollar / Canadian Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "USD-NOK": {
    id: "USD-NOK",
    base: "USD",
    quote: "NOK",
    name: "US Dollar / Norwegian Krone",
    pipSize: 0.0001,
    displayDecimals: 4,
    venueLabel: "Interbank",
  },
  "USD-ZAR": {
    id: "USD-ZAR",
    base: "USD",
    quote: "ZAR",
    name: "US Dollar / South African Rand",
    pipSize: 0.0001,
    displayDecimals: 4,
    venueLabel: "Interbank",
  },
  "USD-TRY": {
    id: "USD-TRY",
    base: "USD",
    quote: "TRY",
    name: "US Dollar / Turkish Lira",
    pipSize: 0.0001,
    displayDecimals: 4,
    venueLabel: "Interbank",
  },
  "USD-MXN": {
    id: "USD-MXN",
    base: "USD",
    quote: "MXN",
    name: "US Dollar / Mexican Peso",
    pipSize: 0.0001,
    displayDecimals: 4,
    venueLabel: "Interbank",
  },
  "USD-CNY": {
    id: "USD-CNY",
    base: "USD",
    quote: "CNY",
    name: "US Dollar / Chinese Yuan",
    pipSize: 0.0001,
    displayDecimals: 4,
    venueLabel: "Interbank",
  },
  "USD-HKD": {
    id: "USD-HKD",
    base: "USD",
    quote: "HKD",
    name: "US Dollar / Hong Kong Dollar",
    pipSize: 0.0001,
    displayDecimals: 5,
    venueLabel: "Interbank",
  },
  "USD-INR": {
    id: "USD-INR",
    base: "USD",
    quote: "INR",
    name: "US Dollar / Indian Rupee",
    pipSize: 0.01,
    displayDecimals: 3,
    venueLabel: "Interbank",
  },
  "USD-KRW": {
    id: "USD-KRW",
    base: "USD",
    quote: "KRW",
    name: "US Dollar / South Korean Won",
    pipSize: 0.01,
    displayDecimals: 2,
    venueLabel: "Interbank",
  },
  "USD-THB": {
    id: "USD-THB",
    base: "USD",
    quote: "THB",
    name: "US Dollar / Thai Baht",
    pipSize: 0.01,
    displayDecimals: 3,
    venueLabel: "Interbank",
  },
  "USD-PLN": {
    id: "USD-PLN",
    base: "USD",
    quote: "PLN",
    name: "US Dollar / Polish Zloty",
    pipSize: 0.0001,
    displayDecimals: 4,
    venueLabel: "Interbank",
  },
};

export function isFxSymbol(symbol: string): boolean {
  return symbol in FX_PAIRS;
}

export function getFxMetadata(symbol: string): FxPairMetadata | undefined {
  return FX_PAIRS[symbol];
}
