import type { CandlePriceBasis, MarketSessionState } from "./quote.js";

export type AssetClass = "crypto" | "metal" | "fx" | "equity" | "etf" | "us_stocks" | "idx_stocks";

export interface MarketSymbol {
  id: string; // Canonical identifier e.g. "BTC-USDT", "EUR-USD", "US:AAPL", "ID:BBCA"
  base: string; // "BTC", "EUR", "AAPL", "BBCA"
  quote: string; // "USDT", "USD", "IDR"
  assetClass: AssetClass;
  provider: string; // "binance", "yahoo", "interbank", "alpaca_iex", "idx_delayed"
  providerSymbol: string; // "BTCUSDT", "EURUSD=X", "AAPL", "BBCA.JK"
  name: string; // "Bitcoin", "Apple Inc.", "Bank Central Asia"
  enabled: boolean;
  isTokenizedMetal?: boolean; // True for PAXG/XAUT (tokenized gold per architecture specification)
  pipSize?: number; // e.g. 0.0001 for EUR/USD, 0.01 for USD/JPY
  displayDecimals?: number; // e.g. 5 for EUR/USD, 3 for USD/JPY, 2 for US, 0 for IDX
  candlePriceBasis?: CandlePriceBasis; // "mid" for FX, "trade" for crypto/equities
  sessionState?: MarketSessionState;
  exchange?: string; // "NASDAQ", "NYSE", "IDX"
  country?: "US" | "ID";
  timezone?: string; // "America/New_York", "Asia/Jakarta"
}

export const DEFAULT_CRYPTO_SYMBOLS: MarketSymbol[] = [
  {
    id: "BTC-USDT",
    base: "BTC",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "BTCUSDT",
    name: "Bitcoin",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "ETH-USDT",
    base: "ETH",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "ETHUSDT",
    name: "Ethereum",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "SOL-USDT",
    base: "SOL",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "SOLUSDT",
    name: "Solana",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "BNB-USDT",
    base: "BNB",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "BNBUSDT",
    name: "BNB",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "XRP-USDT",
    base: "XRP",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "XRPUSDT",
    name: "XRP",
    enabled: true,
    displayDecimals: 4,
    candlePriceBasis: "trade",
  },
  {
    id: "PAXG-USDT",
    base: "PAXG",
    quote: "USDT",
    assetClass: "metal",
    provider: "binance",
    providerSymbol: "PAXGUSDT",
    name: "Paxos Gold (Tokenized Gold)",
    enabled: true,
    isTokenizedMetal: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "DOGE-USDT",
    base: "DOGE",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "DOGEUSDT",
    name: "Dogecoin",
    enabled: true,
    displayDecimals: 4,
    candlePriceBasis: "trade",
  },
  {
    id: "ADA-USDT",
    base: "ADA",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "ADAUSDT",
    name: "Cardano",
    enabled: true,
    displayDecimals: 4,
    candlePriceBasis: "trade",
  },
  {
    id: "AVAX-USDT",
    base: "AVAX",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "AVAXUSDT",
    name: "Avalanche",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "LINK-USDT",
    base: "LINK",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "LINKUSDT",
    name: "Chainlink",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "SUI-USDT",
    base: "SUI",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "SUIUSDT",
    name: "Sui",
    enabled: true,
    displayDecimals: 4,
    candlePriceBasis: "trade",
  },
  {
    id: "NEAR-USDT",
    base: "NEAR",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "NEARUSDT",
    name: "NEAR Protocol",
    enabled: true,
    displayDecimals: 3,
    candlePriceBasis: "trade",
  },
  {
    id: "APT-USDT",
    base: "APT",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "APTUSDT",
    name: "Aptos",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "DOT-USDT",
    base: "DOT",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "DOTUSDT",
    name: "Polkadot",
    enabled: true,
    displayDecimals: 3,
    candlePriceBasis: "trade",
  },
  {
    id: "PEPE-USDT",
    base: "PEPE",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "PEPEUSDT",
    name: "Pepe",
    enabled: true,
    displayDecimals: 8,
    candlePriceBasis: "trade",
  },
  {
    id: "SHIB-USDT",
    base: "SHIB",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "SHIBUSDT",
    name: "Shiba Inu",
    enabled: true,
    displayDecimals: 8,
    candlePriceBasis: "trade",
  },
  {
    id: "ARB-USDT",
    base: "ARB",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "ARBUSDT",
    name: "Arbitrum",
    enabled: true,
    displayDecimals: 4,
    candlePriceBasis: "trade",
  },
  {
    id: "OP-USDT",
    base: "OP",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "OPUSDT",
    name: "Optimism",
    enabled: true,
    displayDecimals: 4,
    candlePriceBasis: "trade",
  },
  {
    id: "RENDER-USDT",
    base: "RENDER",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "RENDERUSDT",
    name: "Render",
    enabled: true,
    displayDecimals: 3,
    candlePriceBasis: "trade",
  },
  {
    id: "INJ-USDT",
    base: "INJ",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "INJUSDT",
    name: "Injective",
    enabled: true,
    displayDecimals: 3,
    candlePriceBasis: "trade",
  },
  {
    id: "TIA-USDT",
    base: "TIA",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "TIAUSDT",
    name: "Celestia",
    enabled: true,
    displayDecimals: 3,
    candlePriceBasis: "trade",
  },
  {
    id: "FET-USDT",
    base: "FET",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "FETUSDT",
    name: "Artificial Superintelligence",
    enabled: true,
    displayDecimals: 4,
    candlePriceBasis: "trade",
  },
  {
    id: "AAVE-USDT",
    base: "AAVE",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "AAVEUSDT",
    name: "Aave",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "ATOM-USDT",
    base: "ATOM",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "ATOMUSDT",
    name: "Cosmos",
    enabled: true,
    displayDecimals: 3,
    candlePriceBasis: "trade",
  },
  {
    id: "FTM-USDT",
    base: "FTM",
    quote: "USDT",
    assetClass: "crypto",
    provider: "binance",
    providerSymbol: "FTMUSDT",
    name: "Fantom",
    enabled: true,
    displayDecimals: 4,
    candlePriceBasis: "trade",
  },
  {
    id: "XAUT-USDT",
    base: "XAUT",
    quote: "USDT",
    assetClass: "metal",
    provider: "binance",
    providerSymbol: "XAUTUSDT",
    name: "Tether Gold (Tokenized Gold)",
    enabled: true,
    isTokenizedMetal: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
];

export const DEFAULT_FX_SYMBOLS: MarketSymbol[] = [
  {
    id: "EUR-USD",
    base: "EUR",
    quote: "USD",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "EURUSD=X",
    name: "Euro / US Dollar",
    enabled: true,
    pipSize: 0.0001,
    displayDecimals: 5,
    candlePriceBasis: "mid",
  },
  {
    id: "GBP-USD",
    base: "GBP",
    quote: "USD",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "GBPUSD=X",
    name: "British Pound / US Dollar",
    enabled: true,
    pipSize: 0.0001,
    displayDecimals: 5,
    candlePriceBasis: "mid",
  },
  {
    id: "USD-JPY",
    base: "USD",
    quote: "JPY",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "USDJPY=X",
    name: "US Dollar / Japanese Yen",
    enabled: true,
    pipSize: 0.01,
    displayDecimals: 3,
    candlePriceBasis: "mid",
  },
  {
    id: "AUD-USD",
    base: "AUD",
    quote: "USD",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "AUDUSD=X",
    name: "Australian Dollar / US Dollar",
    enabled: true,
    pipSize: 0.0001,
    displayDecimals: 5,
    candlePriceBasis: "mid",
  },
  {
    id: "USD-CAD",
    base: "USD",
    quote: "CAD",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "USDCAD=X",
    name: "US Dollar / Canadian Dollar",
    enabled: true,
    pipSize: 0.0001,
    displayDecimals: 5,
    candlePriceBasis: "mid",
  },
  {
    id: "USD-CHF",
    base: "USD",
    quote: "CHF",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "USDCHF=X",
    name: "US Dollar / Swiss Franc",
    enabled: true,
    pipSize: 0.0001,
    displayDecimals: 5,
    candlePriceBasis: "mid",
  },
  {
    id: "NZD-USD",
    base: "NZD",
    quote: "USD",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "NZDUSD=X",
    name: "New Zealand Dollar / US Dollar",
    enabled: true,
    pipSize: 0.0001,
    displayDecimals: 5,
    candlePriceBasis: "mid",
  },
  {
    id: "EUR-JPY",
    base: "EUR",
    quote: "JPY",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "EURJPY=X",
    name: "Euro / Japanese Yen",
    enabled: true,
    pipSize: 0.01,
    displayDecimals: 3,
    candlePriceBasis: "mid",
  },
  {
    id: "GBP-JPY",
    base: "GBP",
    quote: "JPY",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "GBPJPY=X",
    name: "British Pound / Japanese Yen",
    enabled: true,
    pipSize: 0.01,
    displayDecimals: 3,
    candlePriceBasis: "mid",
  },
  {
    id: "USD-IDR",
    base: "USD",
    quote: "IDR",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "USDIDR=X",
    name: "US Dollar / Indonesian Rupiah",
    enabled: true,
    pipSize: 1.0,
    displayDecimals: 2,
    candlePriceBasis: "mid",
  },
  {
    id: "EUR-GBP",
    base: "EUR",
    quote: "GBP",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "EURGBP=X",
    name: "Euro / British Pound",
    enabled: true,
    pipSize: 0.0001,
    displayDecimals: 5,
    candlePriceBasis: "mid",
  },
  {
    id: "EUR-CHF",
    base: "EUR",
    quote: "CHF",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "EURCHF=X",
    name: "Euro / Swiss Franc",
    enabled: true,
    pipSize: 0.0001,
    displayDecimals: 5,
    candlePriceBasis: "mid",
  },
  {
    id: "EUR-AUD",
    base: "EUR",
    quote: "AUD",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "EURAUD=X",
    name: "Euro / Australian Dollar",
    enabled: true,
    pipSize: 0.0001,
    displayDecimals: 5,
    candlePriceBasis: "mid",
  },
  {
    id: "AUD-JPY",
    base: "AUD",
    quote: "JPY",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "AUDJPY=X",
    name: "Australian Dollar / Japanese Yen",
    enabled: true,
    pipSize: 0.01,
    displayDecimals: 3,
    candlePriceBasis: "mid",
  },
  {
    id: "CAD-JPY",
    base: "CAD",
    quote: "JPY",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "CADJPY=X",
    name: "Canadian Dollar / Japanese Yen",
    enabled: true,
    pipSize: 0.01,
    displayDecimals: 3,
    candlePriceBasis: "mid",
  },
  {
    id: "CHF-JPY",
    base: "CHF",
    quote: "JPY",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "CHFJPY=X",
    name: "Swiss Franc / Japanese Yen",
    enabled: true,
    pipSize: 0.01,
    displayDecimals: 3,
    candlePriceBasis: "mid",
  },
  {
    id: "SGD-IDR",
    base: "SGD",
    quote: "IDR",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "SGDIDR=X",
    name: "Singapore Dollar / Indonesian Rupiah",
    enabled: true,
    pipSize: 1.0,
    displayDecimals: 2,
    candlePriceBasis: "mid",
  },
  {
    id: "EUR-IDR",
    base: "EUR",
    quote: "IDR",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "EURIDR=X",
    name: "Euro / Indonesian Rupiah",
    enabled: true,
    pipSize: 1.0,
    displayDecimals: 2,
    candlePriceBasis: "mid",
  },
  {
    id: "GBP-CHF",
    base: "GBP",
    quote: "CHF",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "GBPCHF=X",
    name: "British Pound / Swiss Franc",
    enabled: true,
    pipSize: 0.0001,
    displayDecimals: 5,
    candlePriceBasis: "mid",
  },
  {
    id: "EUR-CHF",
    base: "EUR",
    quote: "CHF",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "EURCHF=X",
    name: "Euro / Swiss Franc",
    enabled: true,
    pipSize: 0.0001,
    displayDecimals: 5,
    candlePriceBasis: "mid",
  },
  {
    id: "NZD-JPY",
    base: "NZD",
    quote: "JPY",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "NZDJPY=X",
    name: "New Zealand Dollar / Japanese Yen",
    enabled: true,
    pipSize: 0.01,
    displayDecimals: 3,
    candlePriceBasis: "mid",
  },
  {
    id: "USD-SGD",
    base: "USD",
    quote: "SGD",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "USDSGD=X",
    name: "US Dollar / Singapore Dollar",
    enabled: true,
    pipSize: 0.0001,
    displayDecimals: 5,
    candlePriceBasis: "mid",
  },
  {
    id: "USD-MYR",
    base: "USD",
    quote: "MYR",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "USDMYR=X",
    name: "US Dollar / Malaysian Ringgit",
    enabled: true,
    pipSize: 0.0001,
    displayDecimals: 4,
    candlePriceBasis: "mid",
  },
  {
    id: "EUR-AUD",
    base: "EUR",
    quote: "AUD",
    assetClass: "fx",
    provider: "interbank",
    providerSymbol: "EURAUD=X",
    name: "Euro / Australian Dollar",
    enabled: true,
    pipSize: 0.0001,
    displayDecimals: 5,
    candlePriceBasis: "mid",
  },
];

export const DEFAULT_US_EQUITY_SYMBOLS: MarketSymbol[] = [
  {
    id: "US:AAPL",
    base: "AAPL",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "AAPL",
    name: "Apple Inc.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:MSFT",
    base: "MSFT",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "MSFT",
    name: "Microsoft Corp.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:NVDA",
    base: "NVDA",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "NVDA",
    name: "NVIDIA Corp.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:TSLA",
    base: "TSLA",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "TSLA",
    name: "Tesla Inc.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:AMZN",
    base: "AMZN",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "AMZN",
    name: "Amazon.com Inc.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:META",
    base: "META",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "META",
    name: "Meta Platforms Inc.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:GOOGL",
    base: "GOOGL",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "GOOGL",
    name: "Alphabet Inc.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:AMD",
    base: "AMD",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "AMD",
    name: "Advanced Micro Devices",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:SPY",
    base: "SPY",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "SPY",
    name: "SPDR S&P 500 ETF Trust",
    exchange: "NYSE",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:QQQ",
    base: "QQQ",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "QQQ",
    name: "Invesco QQQ Trust",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:PLTR",
    base: "PLTR",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "PLTR",
    name: "Palantir Technologies Inc.",
    exchange: "NYSE",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:NFLX",
    base: "NFLX",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "NFLX",
    name: "Netflix Inc.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:COIN",
    base: "COIN",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "COIN",
    name: "Coinbase Global Inc.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:MSTR",
    base: "MSTR",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "MSTR",
    name: "MicroStrategy Inc.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:INTC",
    base: "INTC",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "INTC",
    name: "Intel Corp.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:AVGO",
    base: "AVGO",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "AVGO",
    name: "Broadcom Inc.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:ARM",
    base: "ARM",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "ARM",
    name: "Arm Holdings plc",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:BABA",
    base: "BABA",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "BABA",
    name: "Alibaba Group Holding Ltd.",
    exchange: "NYSE",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:IWM",
    base: "IWM",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "IWM",
    name: "iShares Russell 2000 ETF",
    exchange: "NYSE Arca",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:SMH",
    base: "SMH",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "SMH",
    name: "VanEck Semiconductor ETF",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:SMCI",
    base: "SMCI",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "SMCI",
    name: "Super Micro Computer Inc.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:DIS",
    base: "DIS",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "DIS",
    name: "The Walt Disney Company",
    exchange: "NYSE",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:UBER",
    base: "UBER",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "UBER",
    name: "Uber Technologies Inc.",
    exchange: "NYSE",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:TSM",
    base: "TSM",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "TSM",
    name: "Taiwan Semiconductor Manufacturing",
    exchange: "NYSE",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:ADBE",
    base: "ADBE",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "ADBE",
    name: "Adobe Inc.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:CRM",
    base: "CRM",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "CRM",
    name: "Salesforce Inc.",
    exchange: "NYSE",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:PYPL",
    base: "PYPL",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "PYPL",
    name: "PayPal Holdings Inc.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:ORCL",
    base: "ORCL",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "ORCL",
    name: "Oracle Corporation",
    exchange: "NYSE",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:MU",
    base: "MU",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "MU",
    name: "Micron Technology Inc.",
    exchange: "NASDAQ",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
  {
    id: "US:WMT",
    base: "WMT",
    quote: "USD",
    assetClass: "us_stocks",
    provider: "alpaca_iex",
    providerSymbol: "WMT",
    name: "Walmart Inc.",
    exchange: "NYSE",
    country: "US",
    timezone: "America/New_York",
    enabled: true,
    displayDecimals: 2,
    candlePriceBasis: "trade",
  },
];

export const DEFAULT_IDX_EQUITY_SYMBOLS: MarketSymbol[] = [
  {
    id: "ID:BBCA",
    base: "BBCA",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "BBCA.JK",
    name: "Bank Central Asia Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:BBRI",
    base: "BBRI",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "BBRI.JK",
    name: "Bank Rakyat Indonesia Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:BMRI",
    base: "BMRI",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "BMRI.JK",
    name: "Bank Mandiri Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:BBNI",
    base: "BBNI",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "BBNI.JK",
    name: "Bank Negara Indonesia Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:TLKM",
    base: "TLKM",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "TLKM.JK",
    name: "Telkom Indonesia Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:ASII",
    base: "ASII",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "ASII.JK",
    name: "Astra International Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:ANTM",
    base: "ANTM",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "ANTM.JK",
    name: "Aneka Tambang Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:GOTO",
    base: "GOTO",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "GOTO.JK",
    name: "GoTo Gojek Tokopedia Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:ADRO",
    base: "ADRO",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "ADRO.JK",
    name: "Adaro Energy Indonesia Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:UNVR",
    base: "UNVR",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "UNVR.JK",
    name: "Unilever Indonesia Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:ICBP",
    base: "ICBP",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "ICBP.JK",
    name: "Indofood CBP Sukses Makmur Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:INDF",
    base: "INDF",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "INDF.JK",
    name: "Indofood Sukses Makmur Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:CPIN",
    base: "CPIN",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "CPIN.JK",
    name: "Charoen Pokphand Indonesia Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:KLBF",
    base: "KLBF",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "KLBF.JK",
    name: "Kalbe Farma Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:MDKA",
    base: "MDKA",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "MDKA.JK",
    name: "Merdeka Copper Gold Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:INCO",
    base: "INCO",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "INCO.JK",
    name: "Vale Indonesia Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:BRPT",
    base: "BRPT",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "BRPT.JK",
    name: "Barito Pacific Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:AMMN",
    base: "AMMN",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "AMMN.JK",
    name: "Amman Mineral Internasional Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:PGAS",
    base: "PGAS",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "PGAS.JK",
    name: "Perusahaan Gas Negara Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:ANTM",
    base: "ANTM",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "ANTM.JK",
    name: "Aneka Tambang Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:MEDC",
    base: "MEDC",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "MEDC.JK",
    name: "Medco Energi Internasional Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:SMGR",
    base: "SMGR",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "SMGR.JK",
    name: "Semen Indonesia Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:CPIN",
    base: "CPIN",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "CPIN.JK",
    name: "Charoen Pokphand Indonesia Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:UNTR",
    base: "UNTR",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "UNTR.JK",
    name: "United Tractors Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:INDY",
    base: "INDY",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "INDY.JK",
    name: "Indika Energy Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:BUMI",
    base: "BUMI",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "BUMI.JK",
    name: "Bumi Resources Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:MBMA",
    base: "MBMA",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "MBMA.JK",
    name: "Merdeka Battery Materials Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
  {
    id: "ID:ARTO",
    base: "ARTO",
    quote: "IDR",
    assetClass: "idx_stocks",
    provider: "idx_delayed",
    providerSymbol: "ARTO.JK",
    name: "Bank Jago Tbk",
    exchange: "IDX",
    country: "ID",
    timezone: "Asia/Jakarta",
    enabled: true,
    displayDecimals: 0,
    candlePriceBasis: "trade",
  },
];

export const DEFAULT_SYMBOLS: MarketSymbol[] = [
  ...DEFAULT_CRYPTO_SYMBOLS,
  ...DEFAULT_FX_SYMBOLS,
  ...DEFAULT_US_EQUITY_SYMBOLS,
  ...DEFAULT_IDX_EQUITY_SYMBOLS,
];
