use serde::{Deserialize, Serialize};
use std::env;
use thiserror::Error;

#[derive(Error, Debug)]
pub enum ConfigError {
    #[error("Failed to load configuration: {0}")]
    Load(#[from] config::ConfigError),
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AppConfig {
    pub nats_url: String,
    pub questdb_ilp_host: String,
    pub questdb_ilp_port: u16,
    pub questdb_http_url: String,
    pub valkey_url: String,
    pub gateway_port: u16,
    pub universe: Vec<String>,
    pub hot_symbols: Vec<String>,
    pub candle_1s_retention_days: u32,
    pub binance_ws_url: String,
    pub binance_rest_url: String,
}

impl Default for AppConfig {
    fn default() -> Self {
        Self {
            nats_url: "nats://127.0.0.1:4222".into(),
            questdb_ilp_host: "127.0.0.1".into(),
            questdb_ilp_port: 9009,
            questdb_http_url: "http://127.0.0.1:9000".into(),
            valkey_url: "redis://127.0.0.1:6379".into(),
            gateway_port: 9001,
                        universe: vec![
                "BTC-USDT".into(),
                "ETH-USDT".into(),
                "SOL-USDT".into(),
                "BNB-USDT".into(),
                "XRP-USDT".into(),
                "PAXG-USDT".into(),
                "DOGE-USDT".into(),
                "ADA-USDT".into(),
                "AVAX-USDT".into(),
                "LINK-USDT".into(),
                "SUI-USDT".into(),
                "NEAR-USDT".into(),
                "APT-USDT".into(),
                "DOT-USDT".into(),
                "PEPE-USDT".into(),
                "SHIB-USDT".into(),
                "ARB-USDT".into(),
                "OP-USDT".into(),
                "RENDER-USDT".into(),
                "INJ-USDT".into(),
                "TIA-USDT".into(),
                "FET-USDT".into(),
                "AAVE-USDT".into(),
                "ATOM-USDT".into(),
                "POL-USDT".into(),
                "XAUT-USDT".into(),
                "LTC-USDT".into(),
                "BCH-USDT".into(),
                "ETC-USDT".into(),
                "TRX-USDT".into(),
                "JUP-USDT".into(),
                "UNI-USDT".into(),
                "TON-USDT".into(),
                "ICP-USDT".into(),
                "HBAR-USDT".into(),
                "VET-USDT".into(),
                "FIL-USDT".into(),
                "THETA-USDT".into(),
                "ALGO-USDT".into(),
                "XLM-USDT".into(),
                "FET-USDT".into(),
                "SAND-USDT".into(),
                "MANA-USDT".into(),
                "AXS-USDT".into(),
                "GALA-USDT".into(),
                "CRV-USDT".into(),
                "LDO-USDT".into(),
                "WIF-USDT".into(),
                "COMP-USDT".into(),
                "SNX-USDT".into(),
                "ENS-USDT".into(),
                "WLD-USDT".into(),
                "BONK-USDT".into(),
                "WIF-USDT".into(),
                "JUP-USDT".into(),
                "SEI-USDT".into(),
                "STX-USDT".into(),
                "RUNE-USDT".into(),
                "ORDI-USDT".into(),
                "BONK-USDT".into(),
                "TAO-USDT".into(),
                "GRT-USDT".into(),
                "IMX-USDT".into(),
                "ONDO-USDT".into(),
                "PENDLE-USDT".into(),
                "ENA-USDT".into(),
                "NOT-USDT".into(),
                "FLOKI-USDT".into(),
                "JASMY-USDT".into(),
                "CAKE-USDT".into(),
                "DYDX-USDT".into(),
                "CFX-USDT".into(),
                "RSR-USDT".into(),
                "MASK-USDT".into(),
                "CELO-USDT".into(),
                "ZEC-USDT".into(),
                "NEO-USDT".into(),
                "IOTA-USDT".into(),
                "ZIL-USDT".into(),
                "BAT-USDT".into(),
                "CHZ-USDT".into(),
                "ENJ-USDT".into(),
                "RAY-USDT".into(),
                "PYTH-USDT".into(),
                "JTO-USDT".into(),
                "ETHFI-USDT".into(),
                "STRK-USDT".into(),
                "MANTA-USDT".into(),
                "DYM-USDT".into(),
                "BOME-USDT".into(),
                "SAGA-USDT".into(),
                "PIXEL-USDT".into(),
                "PORTAL-USDT".into(),
                "AEVO-USDT".into(),
                "W-USDT".into(),
                "IO-USDT".into(),
                "ZRO-USDT".into(),
                "PEOPLE-USDT".into(),
                "BLUR-USDT".into(),
                "FLOKI-USDT".into(),
                "XTZ-USDT".into(),
                "EGLD-USDT".into(),
                "FLOW-USDT".into(),
                "KAVA-USDT".into(),
                "ROSE-USDT".into(),
                "ONE-USDT".into(),
                "ANKR-USDT".into(),
                "SKL-USDT".into(),
                "COTI-USDT".into(),
                "SEI-USDT".into(),
                "STX-USDT".into(),
                "QTUM-USDT".into(),
                "RUNE-USDT".into(),
                "RVN-USDT".into(),
                "ONT-USDT".into(),
                "POWR-USDT".into(),
                "CELR-USDT".into(),
                "KAVA-USDT".into(),
                "HOT-USDT".into(),
                "SC-USDT".into(),
                "CTSI-USDT".into(),
                "BAND-USDT".into(),
                "ASTR-USDT".into(),
                "CRV-USDT".into(),
                "DYDX-USDT".into(),
                "BLUR-USDT".into(),
                "TLM-USDT".into(),
                "AUDIO-USDT".into(),
                "SUPER-USDT".into(),
                "YFI-USDT".into(),
                "SUSHI-USDT".into(),
                "CKB-USDT".into(),
                "SSV-USDT".into(),
                "RPL-USDT".into(),
                "GMX-USDT".into(),
                "MAGIC-USDT".into(),
                "OGN-USDT".into(),
                "LQTY-USDT".into(),
                "ACH-USDT".into(),
                "PYTH-USDT".into(),
                "RLC-USDT".into(),
                "MTL-USDT".into(),
                "SFP-USDT".into(),
                "CYBER-USDT".into(),
                "W-USDT".into(),
                "EDU-USDT".into(),
                "DODO-USDT".into(),
                "MAV-USDT".into(),
                "ARKM-USDT".into(),
                "YGG-USDT".into(),
                "STRK-USDT".into(),
                "BEL-USDT".into(),
                "ZRO-USDT".into(),
                "SPELL-USDT".into(),
                "API3-USDT".into(),
                "EIGEN-USDT".into(),
                "RARE-USDT".into(),
                "IO-USDT".into(),
                "WOO-USDT".into(),
                "NOT-USDT".into(),
                "DOGS-USDT".into(),
                "NEIRO-USDT".into(),
                "TURBO-USDT".into(),
                "ORDI-USDT".into(),
                "GAS-USDT".into(),
                "MEME-USDT".into(),
                "AGLD-USDT".into(),
                "BOME-USDT".into(),
                "GALA-USDT".into(),
                "MANA-USDT".into(),
                "SAND-USDT".into(),
                "AXS-USDT".into(),
                "CHZ-USDT".into(),
                "GLMR-USDT".into(),
                "DUSK-USDT".into(),
                "SLP-USDT".into(),
                "PROM-USDT".into(),
                "ENJ-USDT".into(),
                "XAI-USDT".into(),
                "MEME-USDT".into(),
                "TWT-USDT".into(),
                "QNT-USDT".into(),
                "XEC-USDT".into(),
                "OSMO-USDT".into(),
                "FLOW-USDT".into(),
                "LISTA-USDT".into(),
                "BB-USDT".into(),
                "ZK-USDT".into(),
                "REZ-USDT".into(),
                "TNSR-USDT".into(),
                "IOTA-USDT".into(),
                "TURBO-USDT".into(),
                "DOGS-USDT".into(),
                "BANANA-USDT".into(),
                "NEIRO-USDT".into(),
                "HMSTR-USDT".into(),
                "CATI-USDT".into(),
                "SCR-USDT".into(),
                "KAIA-USDT".into(),
                "LUNC-USDT".into(),
                "EUR-USD".into(),
                "GBP-USD".into(),
                "USD-JPY".into(),
                "AUD-USD".into(),
                "USD-CAD".into(),
                "USD-CHF".into(),
                "NZD-USD".into(),
                "EUR-JPY".into(),
                "GBP-JPY".into(),
                "USD-IDR".into(),
                "EUR-GBP".into(),
                "EUR-CHF".into(),
                "EUR-AUD".into(),
                "AUD-JPY".into(),
                "CAD-JPY".into(),
                "CHF-JPY".into(),
                "SGD-IDR".into(),
                "EUR-IDR".into(),
                "GBP-CHF".into(),
                "EUR-SEK".into(),
                "NZD-JPY".into(),
                "USD-SGD".into(),
                "USD-MYR".into(),
                "AUD-NZD".into(),
                "GBP-AUD".into(),
                "EUR-NZD".into(),
                "GBP-NZD".into(),
                "EUR-CAD".into(),
                "GBP-CAD".into(),
                "AUD-CAD".into(),
                "USD-NOK".into(),
                "USD-ZAR".into(),
                "USD-TRY".into(),
                "USD-MXN".into(),
                "USD-CNY".into(),
                "USD-HKD".into(),
                "USD-INR".into(),
                "USD-KRW".into(),
                "USD-THB".into(),
                "USD-PLN".into(),
                "US:AAPL".into(),
                "US:MSFT".into(),
                "US:NVDA".into(),
                "US:TSLA".into(),
                "US:AMZN".into(),
                "US:META".into(),
                "US:GOOGL".into(),
                "US:AMD".into(),
                "US:SPY".into(),
                "US:QQQ".into(),
                "US:PLTR".into(),
                "US:NFLX".into(),
                "US:COIN".into(),
                "US:MSTR".into(),
                "US:INTC".into(),
                "US:AVGO".into(),
                "US:ARM".into(),
                "US:BABA".into(),
                "US:IWM".into(),
                "US:SMH".into(),
                "US:SMCI".into(),
                "US:DIS".into(),
                "US:UBER".into(),
                "US:TSM".into(),
                "US:ADBE".into(),
                "US:CRM".into(),
                "US:PYPL".into(),
                "US:ORCL".into(),
                "US:MU".into(),
                "US:WMT".into(),
                "US:JPM".into(),
                "US:V".into(),
                "US:MA".into(),
                "US:JNJ".into(),
                "US:UNH".into(),
                "US:HD".into(),
                "US:PG".into(),
                "US:KO".into(),
                "US:PEP".into(),
                "US:COST".into(),
                "US:NKE".into(),
                "US:BA".into(),
                "US:CAT".into(),
                "US:GS".into(),
                "US:MS".into(),
                "US:XOM".into(),
                "US:CVX".into(),
                "US:LLY".into(),
                "US:ABBV".into(),
                "US:MRK".into(),
                "US:PFE".into(),
                "US:TMO".into(),
                "US:ABT".into(),
                "US:AMGN".into(),
                "US:ISRG".into(),
                "US:VRTX".into(),
                "US:REGN".into(),
                "US:GILD".into(),
                "US:SNOW".into(),
                "US:SQ".into(),
                "US:RBLX".into(),
                "US:HOOD".into(),
                "US:RIVN".into(),
                "US:LCID".into(),
                "US:SOFI".into(),
                "US:ABNB".into(),
                "US:SNAP".into(),
                "US:PINS".into(),
                "US:TTD".into(),
                "US:ZM".into(),
                "US:DDOG".into(),
                "US:NET".into(),
                "US:CRWD".into(),
                "US:ZS".into(),
                "US:PANW".into(),
                "US:FTNT".into(),
                "US:NOW".into(),
                "US:SHOP".into(),
                "US:MELI".into(),
                "US:SE".into(),
                "US:GRAB".into(),
                "US:NU".into(),
                "US:SPOT".into(),
                "US:NIO".into(),
                "US:ROKU".into(),
                "US:BKNG".into(),
                "US:SBUX".into(),
                "US:MCD".into(),
                "US:GM".into(),
                "US:F".into(),
                "US:T".into(),
                "US:VZ".into(),
                "US:TMUS".into(),
                "US:CSCO".into(),
                "US:IBM".into(),
                "US:QCOM".into(),
                "US:TXN".into(),
                "US:LRCX".into(),
                "US:AMAT".into(),
                "US:KLAC".into(),
                "US:MRVL".into(),
                "US:ON".into(),
                "US:DELL".into(),
                "US:LMT".into(),
                "US:RTX".into(),
                "US:GD".into(),
                "US:DE".into(),
                "US:HON".into(),
                "US:LOW".into(),
                "US:TGT".into(),
                "US:ENPH".into(),
                "US:DKNG".into(),
                "US:MNST".into(),
                "US:LULU".into(),
                "US:BX".into(),
                "US:KKR".into(),
                "US:DASH".into(),
                "US:RKLB".into(),
                "US:IONQ".into(),
                "US:AI".into(),
                "ID:BBCA".into(),
                "ID:BBRI".into(),
                "ID:BMRI".into(),
                "ID:BBNI".into(),
                "ID:TLKM".into(),
                "ID:ASII".into(),
                "ID:ANTM".into(),
                "ID:GOTO".into(),
                "ID:ADRO".into(),
                "ID:UNVR".into(),
                "ID:ICBP".into(),
                "ID:INDF".into(),
                "ID:CPIN".into(),
                "ID:KLBF".into(),
                "ID:MDKA".into(),
                "ID:INCO".into(),
                "ID:BRPT".into(),
                "ID:AMMN".into(),
                "ID:PGAS".into(),
                "ID:MAPI".into(),
                "ID:MEDC".into(),
                "ID:SMGR".into(),
                "ID:MYOR".into(),
                "ID:UNTR".into(),
                "ID:INDY".into(),
                "ID:BUMI".into(),
                "ID:MBMA".into(),
                "ID:ARTO".into(),
                "ID:BRIS".into(),
                "ID:BBTN".into(),
                "ID:BJBR".into(),
                "ID:BJTM".into(),
                "ID:BDMN".into(),
                "ID:NISP".into(),
                "ID:PNBN".into(),
                "ID:MEGA".into(),
                "ID:BNGA".into(),
                "ID:BTPS".into(),
                "ID:PTBA".into(),
                "ID:ITMG".into(),
                "ID:ESSA".into(),
                "ID:HRUM".into(),
                "ID:TINS".into(),
                "ID:ELSA".into(),
                "ID:MYOH".into(),
                "ID:GEMS".into(),
                "ID:BSSR".into(),
                "ID:DSSA".into(),
                "ID:TPIA".into(),
                "ID:AKRA".into(),
                "ID:CTRA".into(),
                "ID:BSDE".into(),
                "ID:SMRA".into(),
                "ID:LPKR".into(),
                "ID:PWON".into(),
                "ID:DMAS".into(),
                "ID:DILD".into(),
                "ID:APLN".into(),
                "ID:KIJA".into(),
                "ID:BKSL".into(),
                "ID:MKPI".into(),
                "ID:PPRO".into(),
                "ID:EXCL".into(),
                "ID:ISAT".into(),
                "ID:TBIG".into(),
                "ID:TOWR".into(),
                "ID:MNCN".into(),
                "ID:SCMA".into(),
                "ID:EMTK".into(),
                "ID:FREN".into(),
                "ID:DCII".into(),
                "ID:BUKA".into(),
                "ID:ERAA".into(),
                "ID:RALS".into(),
                "ID:LPPF".into(),
                "ID:HERO".into(),
                "ID:MIDI".into(),
                "ID:AMRT".into(),
                "ID:ACES".into(),
                "ID:HMSP".into(),
                "ID:GGRM".into(),
                "ID:WIIM".into(),
                "ID:ULTJ".into(),
                "ID:MLBI".into(),
                "ID:GOOD".into(),
                "ID:SIDO".into(),
                "ID:TSPC".into(),
                "ID:DVLA".into(),
                "ID:PYFA".into(),
                "ID:MIKA".into(),
                "ID:HEAL".into(),
                "ID:WIKA".into(),
                "ID:WSKT".into(),
                "ID:PTPP".into(),
                "ID:ADHI".into(),
                "ID:JSMR".into(),
                "ID:WTON".into(),
                "ID:AALI".into(),
                "ID:LSIP".into(),
                "ID:SSMS".into(),
                "ID:DSNG".into(),
                "ID:SIMP".into(),
                "ID:TBLA".into(),
                "ID:SGRO".into(),
                "ID:INTP".into(),
                "ID:SMCB".into(),
                "ID:INKP".into(),
                "ID:TKIM".into(),
                "ID:GJTL".into(),
                "ID:AUTO".into(),
                "ID:SMSM".into(),
                "ID:ARNA".into(),
                "ID:IMPC".into(),
                "ID:GIAA".into(),
                "ID:BIRD".into(),
                "ID:ASSA".into(),
                "ID:TMAS".into(),
                "ID:ADMF".into(),
                "ID:BFIN".into(),
                "ID:PNLF".into(),
                "ID:SRTG".into(),
                "ID:MTEL".into(),
                "ID:BREN".into(),
                "ID:PANI".into(),
                "ID:PGEO".into(),
                "ID:NCKL".into(),
                "ID:RAJA".into(),
                "ID:CITA".into(),
                "ID:SILO".into(),
                "ID:JPFA".into(),
                "ID:MAIN".into(),
                "ID:HOKI".into(),
                "ID:KKGI".into(),
                "ID:NRCA".into(),
                "ID:DUTI".into(),
                "ID:SSIA".into(),
                "ID:BBYB".into(),
                "ID:AGRO".into(),
                "ID:MPMX".into(),
                "ID:TAPG".into(),
            ],
            hot_symbols: vec![
                "BTC-USDT".into(),
                "ETH-USDT".into(),
                "SOL-USDT".into(),
                "PAXG-USDT".into(),
                "EUR-USD".into(),
                "GBP-USD".into(),
                "USD-JPY".into(),
                "US:AAPL".into(),
                "US:NVDA".into(),
                "ID:BBCA".into(),
                "ID:BBRI".into(),
            ],
            candle_1s_retention_days: 30,
            binance_ws_url: "wss://data-stream.binance.vision:9443".into(),
            binance_rest_url: "https://data-api.binance.vision".into(),
        }
    }
}

impl AppConfig {
    pub fn load() -> Result<Self, ConfigError> {
        let _ = dotenvy::dotenv();

        let mut cfg = Self::default();

        if let Ok(v) = env::var("NATS_URL") {
            cfg.nats_url = v;
        }
        if let Ok(v) = env::var("QUESTDB_ILP_HOST") {
            cfg.questdb_ilp_host = v;
        }
        if let Ok(v) = env::var("QUESTDB_ILP_PORT") {
            if let Ok(p) = v.parse() {
                cfg.questdb_ilp_port = p;
            }
        }
        if let Ok(v) = env::var("QUESTDB_HTTP_URL") {
            cfg.questdb_http_url = v;
        }
        if let Ok(v) = env::var("VALKEY_URL") {
            cfg.valkey_url = v;
        }
        if let Ok(v) = env::var("GATEWAY_PORT") {
            if let Ok(p) = v.parse() {
                cfg.gateway_port = p;
            }
        }
        if let Ok(v) = env::var("BINANCE_WS_URL") {
            cfg.binance_ws_url = v;
        }
        if let Ok(v) = env::var("BINANCE_REST_URL") {
            cfg.binance_rest_url = v;
        }
        if let Ok(v) = env::var("UNIVERSE").or_else(|_| env::var("MARKET_UNIVERSE")) {
            cfg.universe = v.split(',').map(|s| s.trim().to_string()).filter(|s| !s.is_empty()).collect();
        }

        Ok(cfg)
    }
}
