[package]
name = "market-domain"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
chrono-tz = "0.10.4"
tokio = { workspace = true }
tokio-postgres = { workspace = true }

[dev-dependencies]
dotenvy = { workspace = true }
